Optimization + Threaded
yohanchatelain/pytracer pull request #19
Opened 2021-06-28 02:01 UTC by niyonx

## Optimization Changes

- Thread-safe multithreading
- Expectedrows estimation for parsing
- Python best practices
- In-kernel Pytables search
- Code changes

2021-06-29 15:13 UTC, yohanchatelain requested changes
I add small comments but it's great work overall Nigel, congrats! :tada:

2021-06-29 15:13 UTC, yohanchatelain commented on pytracer/gui/callbacks.py
> +    # print("update_table_active_cell", e-b)
Remove comments.

2021-06-29 15:13 UTC, yohanchatelain commented on pytracer/gui/callbacks.py
> +    # print("print_heatmap", e-b)
Remove comments

2021-06-29 15:13 UTC, yohanchatelain commented on pytracer/gui/callbacks.py
> +    # b = time.perf_counter()
Remove comments

2021-06-29 15:13 UTC, yohanchatelain commented on pytracer/gui/callbacks.py
> +    # print("print_source", e-b)
Remove comments

2021-06-29 15:13 UTC, yohanchatelain commented on pytracer/gui/callbacks.py
> +    # print("print_modal_source", e-b)
Remove comments

2021-06-29 15:13 UTC, yohanchatelain commented on pytracer/gui/callbacks.py
> +    # print("print_datahover_summary", e-b)
Remove comments

2021-06-29 15:13 UTC, yohanchatelain commented on pytracer/gui/callbacks.py
> +    # print("open_modal_source", e-b)
Remove comments

2021-06-29 15:13 UTC, yohanchatelain commented on pytracer/gui/callbacks.py
> +    # b1 = time.perf_counter()
Remove comments

2021-06-29 15:13 UTC, yohanchatelain commented on pytracer/gui/callbacks.py
> +    # b2 = time.perf_counter()
Remove comments.

2021-06-29 15:13 UTC, yohanchatelain commented on pytracer/gui/callbacks.py
> +    # b3 = time.perf_counter()
Remove comments

2021-06-29 15:13 UTC, yohanchatelain commented on pytracer/gui/callbacks.py
> +    # print("get_scatter_timeline", e-b)
Remove comments.

2021-06-29 15:13 UTC, yohanchatelain commented on pytracer/gui/callbacks.py
> +# @cache.memoize(timeout=TIMEOUT)
Remove comments

2021-06-29 15:13 UTC, yohanchatelain commented on pytracer/gui/callbacks.py
> +            # calls = get_first_call_from_line(lfile, lstart)
Remove comments

2021-06-29 15:30 UTC, niyonx commented on pytracer/core/parser.py
> +            attrs = [*map(lambda value: value[attr], values)]
Just in general map is faster than for loops. You're right though, list comprehension are faster than map, if it requires a lambda. I will revert the map with lambda back to list comprehension!

2021-06-29 15:54 UTC, niyonx commented on pytracer/gui/layout.py
> +import numpy as np
I used np.arange for the start_tiime and end_tiime time generation. I tried multiple approaches and the numpy one was the fastest.

2021-06-29 16:17 UTC, niyonx commented
#17 #18 can be linked as well

2021-06-29 16:55 UTC, yohanchatelain approved these changes

2021-07-05 15:16 UTC, niyonx commented
> #17 #18 can be linked as well

@yohanchatelain is it good to be merged now?

2021-07-06 21:01 UTC, merged